imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Rooty\UserBundle\Entity\User
    registration:
        confirmation:
          enabled: false
        form:
            type: rooty_user_registration
            handler: rooty_user.form.handler.registration
    resetting:
        form:
            type: rooty_user_resetting

avalanche_imagine:
    filters:
        poster:
            type: thumbnail
            options: { size: [300, 500], mode: inset }
        screenshot:
            type: thumbnail
            options: { size: [160, 90], mode: outline }
        avatar_profile:
            type: thumbnail
            options: { size: [200, 400], mode: inset }
        avatar_comment:
            type: thumbnail
            options: { size: [50, 50], mode: outline }
        avatar_message:
            type: thumbnail
            options: { size: [100, 100], mode: outline }

services:
  Rooty.twig.extension:
    class: Rooty\DefaultBundle\Extension\FilesizeExtension
    tags:
      - {name: twig.extension }
  
  Rooty.twig.extension2:
    class: Rooty\DefaultBundle\Extension\UserlinkExtension
    arguments: [@service_container]
    tags:
      - {name: twig.extension }
      
  Rooty.twig.extension3:
    class: Rooty\DefaultBundle\Extension\NumeralExtension
    tags:
      - {name: twig.extension }

  Rooty.twig.extension4:
    class: Rooty\DefaultBundle\Extension\TimeElapsedExtension
    tags:
      - {name: twig.extension }

  Rooty.twig.extension5:
    class: Rooty\DefaultBundle\Extension\DateRelativeExtension
    tags:
      - {name: twig.extension }
      
  Rooty.twig.extension6:
    class: Rooty\DefaultBundle\Extension\RolenameExtension
    arguments: [@service_container]
    tags:
      - {name: twig.extension }
