parameters:
#    rooty_user.example.class: Rooty\UserBundle\Example

services:
#    rooty_user.example:
#        class: %rooty_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    activity_listener:
        class: Rooty\UserBundle\Listener\Activity
        arguments: ["@security.context", "@doctrine"]
        tags:
           - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
        
    rooty_user.registration.form.type:
        class: Rooty\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: rooty_user_registration }
           
    rooty_user.resetting.form.type:
        class: Rooty\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: rooty_user_resetting }
            
    rooty_user.form.handler.registration:
        class: Rooty\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer"]
        scope: request
        public: false